services:
  - type: web
    plan: free
    name: SHProSearchbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/gangstar1010/File-sharing.git      
    branch: main
    envVars:
      - key: TG_BOT_TOKEN 
        sync: false
      - key: OWNER_ID 
        sync: false
      - key: API_ID 
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: API_HASH
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: FORCE_SUB_CHANNEL
        sync: false
      - key: START_MESSAGE
        sync: false
      - key: FORCE_SUB_MESSAGE
        sync: false
      - key: ADMINS
        sync: false
      - key: PROTECT_CONTENT
        sync: false
        sync: false    
    autoDeploy: false
